PREFIX?=	/usr/local
BINDIR:=	$(PREFIX)/bin
LIBDIR:=	$(PREFIX)/lib/bsvc

CC?=		clang
CXX?=		clang++
O:=		o
CFLAGS?=	-O -ansi -pedantic -Wall -Werror -std=c11
CXXFLAGS?=	-O -ansi -pedantic -Wall -Werror -std=c++11

WISH?=		wish
AR:=		ar
RANLIB:=	ranlib
RM:=		rm
INSTALL:=	install
STRIP:=		strip
MKDIR:=		mkdir

MKDEP:=		env CC=$(CC) sh mkdep.sh

include GNUMakefile.common
