PREFIX:=	/opt/local
BINDIR:=	$(PREFIX)/bin
LIBDIR:=	$(PREFIX)/lib/bsvc

CC?=		egcc
CXX?=		eg++
CFLAGS?=	-O -ansi -pedantic -Wall -Werror -std=c11
CXXFLAGS?=	-O -ansi -pedantic -Wall -Werror -std=c++11
O:=		o

WISH?=		wish8.5
AR:=		ar
RANLIB:=	ranlib
RM:=		rm
INSTALL:=	install
STRIP:=		strip
MKDIR:=		mkdir

MKDEP:=		env CC=$(CC) sh mkdep.sh

include GNUMakefile.common
